---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-app-deployment
  namespace: bggns
  labels:
    app: bgg
    name: bgg-app-deployment
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bgg
      name: bgg-app-pod
  template:
    metadata:
      name: bgg-app-pod
      labels:
        app: bgg
        name: bgg-app-pod
    spec:
      containers:
      - name: bgg-app-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bgg-config
        - secretRef:
            name: bgg-secret
        ports:
        - name: bgg-app-port
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bgg-app-service
  namespace: bggns
  labels:
    app: bgg
    name: bgg-app-service
spec:
  type: ClusterIP
  # type: NodePort
  # type: LoadBalancer
  selector:
    app: bgg
    name: bgg-app-pod
  ports:
  - port: 3000
    targetPort: bgg-app-port